### PR TITLE
add CI/CD

### LINKED ISSUE #15: CI/CD Pipeline
Build a CI/CD Pipeline to support both testing and subsequent deployments. 
This will also support regenerating static assets.

### PR DESCRIPTION
**Pull request by bleything**
Updates the Terraform code to deploy a CI/CD pipeline for the demo application. See discussion in #15.

- [X] create Cloud Source Repository repo as a push-to-deploy target
- [X] create build trigger that runs `npm test`
- [X] update trigger to push image
- [X] update trigger to deploy to cloud run

/closes #15

### CODE REVIEW

**Comment by bleything** [comment]
Alright, here's a simple pipeline. I still need to do some cleanup and update the README but here's how you can get started:

- run `terraform apply`, it'll spit out a CSR repo url
- clone [my fork of the sample app](https://github.com/bleything/mean-stack-example) and switch to the `omnibus` branch
- in your working copy of the sample app, run `git remote add csr <your CSR url>`
- `git push csr omnibus:main`
- go to [the build history page](https://console.cloud.google.com/cloud-build/builds) to watch your build go

Let me know if you run into any issues at all, no matter how small. There's some finicky stuff in here and I'd like to sort it out if possible.

I'll update when everything's working right and I have docs.

**Comment by bleything** [comment]
FYI - I reworked my original commits to use a module instead of creating resources in the root module. This makes it easier to put behind a feature flag, because you can just turn the module on or off instead of having to make every resource conditional.

Anyway, that's what the force push was about.

**Comment by bleything** [comment]
... turns out the module idea, while conceptually sound, creates more problems than it solves right now. we can revisit that change later, but for now I'm reverting it.

**Comment by bleything** [comment]
@villasenor for some reason I can't mark you as a reviewer but please take a look if you've got a few minutes.

**Comment by mikegcoleman** [comment]
LGTM

**Review by villasenor — APPROVED** [review]
looks great!

**Pull request merged**
